# Recognitions
- platform: LinkedIn
  date: Aug, 2023
  url: https://www.linkedin.com/embed/feed/update/urn:li:share:7097844714871091200
  translation: >-
    Huge congratulations to Jakob Jersild Nielsen 🌟 On the 8th of August, he
    defended his Master's thesis in computational biomedicine and earned an
    impressive grade of A 🏆 👏 🤩<br><br> The thesis focuses on improving the
    diagnosis of pancreatic cancer, which is among the deadliest forms of
    cancer.<br><br> The high mortality rate is largely due to late diagnosis
    since patients in the early stages often show no symptoms, the symptoms in
    general are non-specific, and the current screening methods are
    ineffective.<br><br> Analysis of ctDNA (DNA released from tumors into the
    plasma) using next-generation sequencing has proven effective for cancer
    prognosis and monitoring. However, the application of this method is
    currently hindered by technical limitations. Jakob's research aims to
    enhance the existing ctDNA detection tools 👨⚕️ 🛠 ⚗ 🔬<br><br> At the
    Clinical Genetic Department, Jakob was guided by Professor Torben Kruse,
    Professor Mads Thomassen, Lars Andersen, and Kristina Magaard
    Koldby.<br><br>
  dimensions:
    - screen: 600
      post_height: 1035
      translation_height: 400
    - screen: 550
      post_height: 1065
      translation_height: 420
    - screen: 500
      post_height: 1055
      translation_height: 440
    - screen: 450
      post_height: 1105
      translation_height: 530
    - screen: 400
      post_height: 1110
      translation_height: 570
    - screen: 350
      post_height: 1205
      translation_height: 670
